common: &common
  adapter: postgresql
  username: jeff
  password:
  host: localhost
  reconnect: true
  min_messages: warning
  prepared_statements: false

development:
  <<: *common
  database: rsvp_development

test:
  <<: *common
  database: rsvp_test

production:
  <<: *common
  database: rsvp_production

edge:
  <<: *common
  database: rsvp_edge
