common: &common
  adapter: postgresql
  username: jeff
  password:
  host: localhost
  reconnect: true

development:
  <<: *common
  database: rsvp_development

test:
  <<: *common
  database: rsvp_test

