common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  socket: /opt/boxen/data/mysql/socket

development:
  <<: *common
  database: rsvp_development

test:
  <<: *common
  database: rsvp_test

production:
  <<: *common
  database: rsvp_production

edge:
  <<: *common
  database: rsvp_edge
